sudo: false
language: ruby
bundler_args: --without kitchen
script:
  - bundle exec rake lint
  - bundle exec rake validate
  - bundle exec rake spec
matrix:
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION="= 3.7.3" DEPLOY="true"
  - rvm: 1.9.3
    env: PUPPET_VERSION="= 3.7.3" FUTURE_PARSER="yes"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.0"
deploy:
  provider: puppetforge
  on:
    tags: true
    branch: master
    condition: "$DEPLOY = true"
  user:
    secure: "BttXI+JzvGXNXFeVlw+cxjNa+YTEZMiQPJ7Zf4dhD4EBRvqA1GxdgVv5ubO44pCjZsDwT/e4bNqr9ZiUIrYiboK2d41t1yMyPrtGNMo1KGIu7LIrR5d3pKBkPk28cuHOVt6YpV1HZiutKBGgpMux1GVhkp/swemFMQHQhCB4BC0XiliiEHt9XwKHnC9FyXIE2OKtvgdyvrKQ5TyFO7W4cyXVUVvxowIUVfLzGJK6L5e/osmwjwdZkKRAB2qE47CtZstDdkmP6d1x2fT4yxJToJb3ZfSrdMLcqRzOoGpAItBLoiRrPjkKImSjf9HPWZsSG4WyYT04cNnR4vREpi73lS3yR4u7SR77dSrjOxWqNWkHt9fBQczzGl1JojKdki6guNzNnG/SkV7Un2xeom2XTzId9Ex55a6hto7GHiG4L/5WCX4iyC77q5XAd02gD2E2JKHAv19TWU4r+0TpIIrf02AhOIwKqKExzeImjC3r7J/KYfgBkkcdrXJz0NnmcoWzoeCsZbu/rV/qHG2SYt6YEjYKqFnUTh9mADlrfg/Slry5xnX4NDsAARWzya5bxuKPX5atrZQZEG2mMYVTcw3+CU5EbgNQnfzDhH9aeLnEg44FudJtmWakiGwUVy/smyTp8zkX3+vFqg/ffWEmkFjp3jVAijPjIFf6fRqBT+qUp4w="
  password:
    secure: "E7tdOffUd4XMA0Sgzd8kSuKYtw3Hy41C2SBVuYFCYRFSXj/XclEE0W9xk6xBJmTkrZ8RyR5MZ5gHI12/EUFR/SD+heGrGgL3A+BREck01WHOFhfOSysddzd4nNahmNiXHWKy2mBJorD1yng46CHyAdjlP4WYtqc1vF3zDmUjkPp95F2NKVqRNen9nPI6dcAUCFC195I9HhkBJSgXvrJ+KPKOKHIfHCRji72vGO5yG6jpbk1ZAT1B0cUEsgrnHnTXWaym2JxsJQxtAJP7sufbRHWznzhlJtdaPOu/dK+2oRfzd+ZUJLDULCoUMqbQ1G9xNZNpRdjfn4QCjMpRlvYq1dDjV3+qWzULJfsNMrNO4eOVEnj8LYgS81Dwh4NiFB3BgWJlf8eeiR3Pb93vWsbTRmTrcDCWFPkb7LtYuV8vfJexYVDAb6qkBIzzZzbvcBKeZ38sNOqEwyfPj+pFN2KwoMiz8lYEucPt8k9vEGkBjmG41rXWckxE8stwjTXTZhqC4Of4UT2kVtysF+VGbV5ySpRV7/0VOI/NlZMYBpyE73dNu49cZtjnAsQhVr3Kxon983hF1vc5JtMXOFHglgqRpfbzVGZEOTT7pNsQfR9b03Fh3T3DoXcPJnsarJf9ELFKZU3xuKsTo90uNCAiY8A29bEufzUw92Oli1tPz2/gEGc="
